export enum TYPES {
  ADD_USER = "ADD_USER",
  LOGOUT_USER = "LOGOUT_USER",
  ADD_SOCKET_CONNECTION_OBJECT = "ADD_SOCKET_CONNECTION_OBJECT",
  DISCONNECT_SOCKET_CONNECTION = "DISCONNECT_SOCKET_CONNECTION",
}
