export enum TYPES {
  ADD_USER = "ADD_USER",
  LOGOUT_USER = "LOGOUT_USER",
  ADD_SOCKET_CONNECTION_OBJECT = "ADD_SOCKET_CONNECTION_OBJECT",
  DISCONNECT_SOCKET_CONNECTION = "DISCONNECT_SOCKET_CONNECTION",
}

export enum CHATTYPES {
  ADD_MESSAGE = "ADD_MESSAGE",
  ADD_CONVERSATIONS = "ADD_CONVERSATIONS",
  LOAD_MESSAGES_DATA = "LOAD_MESSAGES_DATA",
}
